<?php
  $this->assign('menuItem', 'product_productslist');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/product/list') ?>">商品列表</a></span></li>
		<li><span class="basic"><?php echo t('Copy') ?> - <?php echo plain($product->name . ' (' . $product->sn . ')') ?></span></li>
	</ul>
</div>

<div>
    <?php echo themeMessages() ?>
    <form action="" method="post" id="form_productinfo">
    <input type="hidden" id="pid" value="<?php if (isset($product) && isset($product->pid)) echo $product->pid ?>">
    <input type="hidden" id="directory_list" value='<?php echo strtr(json_encode($directoryList), "'", "\'") ?>'>
    <div class="clear left_photo" id="tabs">
      <div class="clear tab_ul">
      <ul>
        <li><a href="#base"><?php echo t('Base information') ?></a></li>
      </ul>
      </div>
      <div id="base" class="box_Product main_right">
      <table>
        <tr class="nohover"><td class="bold" colspan="2">货号</td></tr>
        <tr>
          <td colspan="2">商品内部货号:<?php if (isset($product)) echo plain($product->sn) ?></td>
        </tr>
        <tr class="nohover"><td class="bold" colspan="2">商品名称</td></tr>
        <tr>
          <td colspan="2">商品名称:<?php if (isset($product)) echo plain($product->name) ?></td>
        </tr>
        <tr class="nohover"><td class="bold" colspan="2">商品目录</td></tr>
        <tr>
          <td><p><select name="directory_tid1">
            <option value="0">-- 请选择一级商品目录 --</option>
<?php foreach ($directoryList as $tid1 => $term1): ?>
            <option value="<?php echo $tid1 ?>"<?php if (isset($product) && isset($product->directory_tid1) && $product->directory_tid1 == $tid1) echo ' selected="selected"' ?>><?php echo t($term1->name) ?></option>
<?php endforeach ?>
          </select></p>
          <p><select name="directory_tid2">
            <option value="0">-- 请选择二级商品目录 --</option>
<?php
  if (isset($product->directory_tid1) && isset($directoryList[$product->directory_tid1]) && isset($directoryList[$product->directory_tid1]->sub)):
    foreach ($directoryList[$product->directory_tid1]->sub as $tid2 => $term2):
?>
            <option value="<?php echo $tid2 ?>"<?php if (isset($product) && isset($product->directory_tid2) && $product->directory_tid2 == $tid2) echo ' selected="selected"' ?>><?php echo t($term2->name) ?></option>
<?php
    endforeach;
  endif;
?>
          </select></p>
          <p><select name="directory_tid3">
            <option value="0">-- 请选择三级商品目录 --</option>
<?php
  if (isset($product->directory_tid2) && isset($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]) && isset($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]->sub)):
    foreach ($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]->sub as $tid3 => $term3):
?>
            <option value="<?php echo $tid3 ?>"<?php if (isset($product) && isset($product->directory_tid3) && $product->directory_tid3 == $tid3) echo ' selected="selected"' ?>><?php echo t($term3->name) ?></option>
<?php
    endforeach;
  endif;
?>
          </select></p>
          <p><select name="directory_tid4">
            <option value="0">-- 请选择四级商品目录 --</option>
<?php
  if (isset($product->directory_tid3) && isset($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]->sub[$product->directory_tid3]) && isset($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]->sub[$product->directory_tid3]->sub)):
    foreach ($directoryList[$product->directory_tid1]->sub[$product->directory_tid2]->sub[$product->directory_tid3]->sub as $tid4 => $term4):
?>
            <option value="<?php echo $tid4 ?>"<?php if (isset($product) && isset($product->directory_tid4) && $product->directory_tid4 == $tid4) echo ' selected="selected"' ?>><?php echo t($term4->name) ?></option>
<?php
    endforeach;
  endif;
?>
          </select></p>
          </td>
          <td>商品所属目录</td>
        </tr>
      </table>
    	</div>
    
    <div class="attribute" style="margin-top:10px; margin-left:30px; margin-bottom:30px;">
      <input type="submit" value="保存" class="Buttom_1 but" />
      <a href="<?php echo url('admin/product/list') ?>" class="Buttom_back but">返回商品列表</a>
    </div>
    </div>
    </form>
  </div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
