<?php
$this->assign('menuItem', 'product_productdirectorylist');
echo $this->render('admin/before_body.phtml');
echo $this->render('admin/header.phtml');
?>

<div class="import clear">
<ul>
	<li><span class="check"><a href="<?php echo url('admin/product/productdirectorylists') ?>">商品目录列表</a></span></li>
	<li><span class="check"><a href="<?php echo url('admin/product/list') ?>">商品列表</a></span></li>
</ul>
</div>

<div class="main_right" style="margin-top: 5px; margin-left: 5px;"><?php echo themeMessages() ?>
	<form id="form_productdirectory" action="<?php echo url('admin/product/productdirectorylists') ?>" method="post" enctype="multipart/form-data">
		<input type="hidden" id="directory_list" value='<?php echo strtr(json_encode($directoryList), "'", "\'") ?>'>
		<table>
			<tr class="nohover"><td class="bold" colspan="2"><?php echo "商品目录权重 管理 > ".t('Product Dir');?></td></tr>
            <tr><td colspan="2"><select name="directory_tid1" onchange="selectChange(this)" class="directory_tid1" id="dp1">
            <option value="0">-- 请选择一级商品目录 --</option>
<?php foreach ($directoryList as $tid1 => $term1): ?>
            <option value="<?php echo $tid1 ?>"><?php echo t($term1->name) ?></option>
<?php endforeach ?>
          </select>
          <select name="directory_tid2" onchange="selectChange(this)" class="directory_tid2" id="dp2">
            <option value="0">-- 请选择二级商品目录 --</option>
          </select>
          <select name="directory_tid3" onchange="selectChange(this)" class="directory_tid3" id="dp3">
            <option value="0">-- 请选择三级级商品目录 --</option>
          </select>
          <select name="directory_tid4" onchange="selectChange(this)" class="directory_tid4" id="dp4">
            <option value="0">-- 请选择四级商品目录 --</option>
          </select>

          
          </td></tr>
			<tr class="nohover">
				<td>
				  <input type="submit" value="确定" class="btn productdirectoryButton" style="float:left;">
				</td>
			</tr>
		</table>
	</form>
</div>

<div id="products_list_page">
    <?php echo themeMessages() ?>
    <div class="clear left_photo" id="tabs">
      <div class="clear tab_ul">
	      <ul>
	        <li>
	        	<a href="#list"><?php echo t('List') ?></a>
	        </li>
	      </ul>
      </div>
      

      <div id="list"  class="box_Product main_right">
      	<div class="pagination" style="margin-left:10px"><?php echo $pagination ?></div>
	  	<div style="clear:both; margin-bottom:10px;" ></div>
        <form id="form1" action ="<?php echo url('admin/product/productdirectoryliststrans') ?>" method="post">
          <table id="products_list">
          <tr class="subhead">
            <td width="5%">ID</td>
            <td width="7%"><?php echo t('SN') ?></td>
            <td width="7%"><?php echo t('Product Number') ?></td>
            <td width="*"><?php echo t('Product Name') ?></td>
            <td width="8%"><?php echo t('Directory') ?></td>
            <td width="6%"><?php echo t('Price') ?></td>
            <td width="5%"><?php echo t('Inventory') ?></td>
            <td width="5%"><?php echo t('Status') ?></td>
            <td width="5%"><?php echo t('Brand') ?></td>
            <td width="3%"><?php echo t('Weight') ?></td>
            <td width="7%"><?php echo t('Type') ?></td>
            <td width="*"><?php echo t('Options') ?></td>
          </tr>
          <?php
  if(access('edit product'))$ce='ce';else $ce='';
  foreach($productsList as $pid => $product):
?>
          <tr class="i<?php echo $pid."dp".$product->directP ?>">
            <td><?php echo plain($product->pid) ?></td>
            <td class="sn"><?php echo plain($product->sn) ?></td>
            <td class="nu"><?php echo plain($product->number) ?></td>
            <td class="na"><?php echo plain($product->name) ?></td>
            <td class="dt<?php if (isset($product->directory_tid)) echo ' ' . $product->directory_tid ?>"><?php echo isset($directoryTermsList[$product->directory_tid]) ? plain($directoryTermsList[$product->directory_tid]->name) : '-' ?></td>
            <td class="sp"><?php echo c($product->sell_price, Bl_Config::get('currency'), false) ?></td>
            <td class="st"><?php echo $product->stock ?></td>
            <td class="sa<?php if (isset($product->status)) echo ' ' . ($product->status ? 2 : 1) ?>"><?php echo $product->status == Product_Model::STATUS_PUBLISHED ? t('Published') : t('Unpublished') ?></td>
            <td class="bt<?php if (isset($product->brand_tid)) echo ' ' . $product->brand_tid ?>"><?php echo isset($brandList[$product->brand_tid]) ? plain($brandList[$product->brand_tid]->name) : '-' ?></td>
            <td class="<?php echo $ce;?> wt"><?php echo number_format($product->weight) ?></td>
            <td><?php echo isset($typeList[$product->type]) ? plain($typeList[$product->type]->name) : '-'?></td>
            <td>
              <a href="<?php echo url($product->url) ?>" target="_blank"><?php echo t('View') ?></a>
<?php if(access('edit product')): ?>
              <a href="<?php echo url('admin/product/edit/' . $pid) ?>"><?php echo t('Edit') ?></a>
<?php endif; ?>
<?php //if(access('copy product')): ?>
			  <!-- <a href="<?php echo url('admin/product/copy/' . $pid) ?>"><?php echo t('Copy') ?></a> -->
<?php //endif; ?>
<?php if(access('manage comment')): ?>
              <a href="<?php echo url('admin/comment/insert/' . $pid) ?>">添加评论</a>
<?php endif; ?>
<?php if (access('delete product image cache')): ?>
              <a href="<?php echo url('admin/product/deletecache/' . $pid ) ?>" class="btn_confirm" rel="确认删除缓存吗?">清空缓存图片</a>
<?php endif ?>
            </td>
          </tr>
<?php
  endforeach;
?>
          </table>
          <div></div>
          <div class="pagination" style="margin-left:10px"><?php echo $pagination ?></div>
          <div style="clear:both; margin-bottom:10px;" ></div>
        </form>
      </div>
    </div>
  </div>

<?php
	echo $this->render('admin/footer.phtml');
	echo $this->render('admin/after_body.phtml');
?>
          <script>
          	<?php if($dp1 != 0): ?>
          		var dp1 = document.getElementById('dp1');
          		dp1.value = <?php echo $dp1; ?>;
          		dp1.addEventListener("change", selectChange(dp1), false);
          	<?php endif; ?>
          	
          	<?php if($dp2 != 0): ?>
	      		var dp2 = document.getElementById('dp2');
	      		dp2.value = <?php echo $dp2; ?>;
	      		dp2.addEventListener("change", selectChange(dp2), false);
	      	<?php endif; ?>
	      	
	      	<?php if($dp3 != 0): ?>
		  		var dp3 = document.getElementById('dp3');
		  		dp3.value = <?php echo $dp3; ?>;
		  		dp3.addEventListener("change", selectChange(dp3), false);
		  	<?php endif; ?>
		  	
		  	<?php if($dp4 != 0): ?>
				var dp4 = document.getElementById('dp4');
				dp4.value = <?php echo $dp4; ?>;
				dp4.addEventListener("change", selectChange(dp4), false);
			<?php endif; ?>
          </script>