<?php
  $this->assign('menuItem', 'product_typelist');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/product/typelist') ?>">商品类型列表</a></span></li>
		<?php if (access('edit type')): ?>
		<li><span class="new"><a href="<?php echo url('admin/product/typeedit') ?>">新建商品类型</a></span></li>
		<?php endif;?>
	</ul>
</div>

<div class="main_right">
    <?php echo themeMessages() ?>
    <table>
    <tr class="subhead">
      <td width="10%">类型标识</td>
      <td width="35%">类型名称</td>
      <td width="20%">商品数量</td>
      <td width="30%"><?php if (access(array('edit type', 'delete type'), 'or')): ?>选项<?php endif ?></td>
    </tr>
<?php
  foreach($typeList as $key => $type):
?>
    <tr>
      <td><?php if (access('edit type')): ?><a href="<?php echo url('admin/product/typeedit/' . $type->type) ?>"><?php endif;?>
      <?php echo plain($type->type) ?><?php if (access('edit type')): ?></a><?php endif;?></td>
      <td><?php if (access('edit type')): ?><a href="<?php echo url('admin/product/typeedit/' . $type->type) ?>"><?php endif;?>
      <?php echo plain($type->name) . (trim($type->name_cn) !== '' ? (' (' . plain(trim($type->name_cn)) . ')') : '') ?>
      <?php if (access('edit type')): ?></a><?php endif;?></td>
      <td><?php echo plain($type->productsCount) ?></td>
      <td>
        <?php if (access('edit type')): ?><a href="<?php echo url('admin/product/typeedit/' . $type->type) ?>">编辑</a><?php endif;?>
        <?php if (access('delete type')): ?>
        <a href="<?php echo url('admin/product/typedelete/' . $type->type) ?>" class="btn_confirm" rel="确认删除该类型吗?">删除</a>
        <?php endif;?>
      </td>
    </tr>
<?php
  endforeach;
?>
    </table>
	</div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
