<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <?php $this->render('parts/metaandtitle.phtml'); ?>
	<?php $this->render('parts/includecss.phtml', array('colorchart' => true)); ?>
	<?php $this->render('parts/includejs.phtml'); ?>
</head>
<body>
	<div class="head">
		<?php echo $this->render("parts/header.phtml"); ?>
    </div>
    <div class="about_us" style="font:1.2rem/2rem 'arial';padding:0 4.5%;margin-top:5px;">
        <span style="font:1.7rem/2.3rem 'arial';font-weight:bold"><?php echo $articleInfo->title; ?></span><br/>
        <?php echo $this->render('articles/'.$articleInfo->path_alias . ".phtml"); ?>
    </div>
    
	<div class="col-box" style="font-size: 133.33%">
		<?php // echo $this->render('modules/collapsemenu.phtml'); ?>
	</div>
	<a class="back_to_top" href="#">
		<span></span><br/>TOP OF PAGE
	</a>
	<div class="foot">
		<?php echo $this->render('parts/footer.phtml'); ?>
	</div>
    <script src="<?php echo $tpldir; ?>/javascripts/main.js" type="text/javascript"></script>
</body>
<?php $this->render('parts/after_body.phtml'); ?>
</html>