<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <?php $this->render('parts/metaandtitle.phtml'); ?>
	<?php $this->render('parts/includecss.phtml'); ?>
	<?php $this->render('parts/includejs.phtml'); ?>
</head>
<body>
    <!--头部-->
    <div class="head">
		<?php echo $this->render("parts/header.phtml"); ?>
    </div>
    <!-- shop by -->
    <div id="cat2">
        <div class="catalogue">
            <div class="searchbox">
                <div class="kuang">
                    <form name="searchform" action="<?php echo url("pitems"); ?>" method="post">
	    				<input name="keyword" class="search" type="text" id="keywordinput" placeholder="Search...">
	    			</form>
                    <div class="sou">Go</div>
                    <div class="clear"></div>
                </div>
            </div>
            <script>
		    	$('.sou').click(function(){
				    var key = $("#keywordinput").val();
				    if(key){searchform.submit();}
				});
	    	</script>
        </div>
        
        <div class="col-box">
        	<?php echo $this->render('modules/collapsemenu.phtml'); ?>
        </div>
		<a class="back_to_top" href="#">
			<span></span><br/>TOP OF PAGE
		</a>
        <div class="foot">
    		<?php echo $this->render('parts/footer.phtml'); ?>
    	</div>
    </div>
    <script src="<?php echo $tpldir; ?>/javascripts/main.js" type="text/javascript"></script>
</body>
<?php $this->render('parts/after_body.phtml'); ?>
</html>