<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <?php $this->render('parts/metaandtitle.phtml'); ?>
	<?php $this->render('parts/includecss.phtml'); ?>
	<?php $this->render('parts/includejs.phtml'); ?>
</head>
<body>
<div class="sign_regist_head">
    <img src="<?php echo $tpldir; ?>/images/ad_head.png">
</div>
<h2 class="recover_h2">Check Your E-mail</h2>
<p class="success-word" style="margin-top: 0.5rem;">
    We’ve sent an e-mail massage to <span><?php echo $email; ?></span>
    Please click on the link to an Adoringdress.com page where
    you can create a new password
</p>
</body>
<?php $this->render('parts/after_body.phtml'); ?>
</html>
