<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <?php $this->render('parts/metaandtitle.phtml'); ?>
	<?php $this->render('parts/includecss.phtml'); ?>
	<?php $this->render('parts/includejs.phtml'); ?>
</head>
<body>
    <div class="sign_regist_head">
        <a href="/">
        	<img src="<?php echo $tpldir; ?>/images/ad_head.png">
        </a>
    </div>
    <?php echo themeMessages(); ?>
<!--     <p class="failure-word"> -->
<!--         We’re sorry. we weren’table to identify you given the -->
<!--         information provided. -->
<!--     </p> -->
    <div class="sign_regist">
    <h1>Recovery Password</h1>
    <p class="recover_remind">
        Enter your email address below and we'll send
        you an email message containing your new
        password.
    </p>
    
    <form action="<?php echo url('user/getPassword/')?>" method="post">
	    <h2 class="sign_regist_h2">Email Address:</h2>
	    <input name="email" class="sign_regist_input" type="text"/>
	
	    <button type="submit" class="regist_button">Submit</button>
    </form>
    
    <div class="foot">
        <div class="di">
            <p class="ditu">CopyRight © Cheap-Lingerie.com</p>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.sign_regist_input').click(function(){
        $('input').removeClass('aaa')
        $(this).addClass('aaa')
    })
</script>
</body>
<?php $this->render('parts/after_body.phtml'); ?>
</html>