<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<style>
		html,body{
          width:100%;
          height:100%;  
        }
        .paytransfer-loadding {
          width: 100%;
          height: 100%;
          text-align: center; }
        .paytransfer-loadding table {
          width: 100%;
          height: 100%; }
        .paytransfer-loadding table td {
          vertical-align: middle; }
        .paytransfer-loadding table td img {
          vertical-align: middle;
          display: inline-block;
          width: 25%;
          border-radius: 15px; }
        .paytransfer-loadding table td span {
          display: block;
          font: 3rem/4rem 'arial';
          color: #000000;
          font-style: italic; }
    	</style>
	</head>
	<body>
		<div style="display:none">
		<?php if(! isset($orderInfo->payment->online) || $orderInfo->payment->online) :
		 echo isset($submitform) ? $submitform : null;
		 endif;
		 ?>
		</div>
		<div class="paytransfer-loadding">
	    	<table>
	            <tr>
	                <td>
	                    <img src="<?php echo themeResourceURI('/images/loading.gif')?>">
		                <span>Loading...</span>
		             </td>
		        </tr>
		  </table>
        </div>
		<script>
			window.onload = function(){
				$('form').submit();
			};
		</script>
    </body>
    <script src="<?php echo $tpldir. '/javascripts/jquery-2.1.1.min.js';?>" type="text/javascript"></script>
    <?php $this->render('parts/after_body.phtml'); ?>
</html>