<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
	<head>
	    <?php $this->render('parts/metaandtitle.phtml'); ?>
		<?php $this->render('parts/includecss.phtml'); ?>
		<?php $this->render('parts/includejs.phtml'); ?>
	</head>
	<body>
		<div class="back_head">
		    <a class="back" href="<?php echo url($product->url); ?>"><img src="<?php echo $tpldir; ?>/images/back.png"></a>
		</div>
		<h2 class="classh2">Reviews</h2>
		
		<div class="review">
			<div class="ave">
				<p>Average Rating</p>
				<span class="star">
					<?php for($i = 0; $i < floor($star); $i++ ): ?>
						<a><img src="<?php echo $tpldir; ?>/images/starfill.png" /></a>
					<?php endfor; ?>
					<?php if((ceil($star) - floor($star)) == 1): ?>
						<a><img src="<?php echo $tpldir; ?>/images/starhalf.png" /></a>
					<?php endif; ?>
					<?php for($i = 0; $i < 5 - ceil($star); $i++): ?>
						<a><img src="<?php echo $tpldir; ?>/images/star.png" /></a>
					<?php endfor; ?>
					<div class="clear"></div>
				</span>
				<div class="clear"></div>
			</div>
			<?php if($canComment): ?>
				<div class="col-box">
					<a href="<?php echo url('product/writereview/'.$product->pid); ?>">
						<button class="btn-long">Write a Review</button>
					</a>
				</div>
			<?php endif; ?>
			
			<?php echo $this->render('ajax/ajaxshowmorereviews.phtml'); ?>
		</div>
		<div class="col-box">
			<button class="btn-long" offset="2" id="showmore">Show More</button>
		</div>
		<script>
			$("#showmore").click(function(){
				var offset = $("#showmore").attr("offset");
				$.ajax({
					type:"POST",
					url:'<?php echo url('product/ajaxshowmorereviews'); ?>',
					data:{ offset : offset, pid : <?php echo $product->pid; ?> },
					success: function(data){
						$(".review").append(data);
						$("#showmore").attr("offset", parseInt(offset) + 1);
			        }
			    });
			});
		</script>
		<a class="back_to_top" href="#">
			<span></span><br/>
			TOP OF PAGE
		</a>
	</body>
	<?php $this->render('parts/after_body.phtml'); ?>
</html>