<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <?php $this->render('parts/metaandtitle.phtml'); ?>
	<?php $this->render('parts/includejs.phtml'); ?>
	<link href="<?php echo $tpldir; ?>/css/color_chart.css" rel="stylesheet" type="text/css">
    <script src="<?php echo $tpldir; ?>/javascripts/color-chart-gaitupian.js" type="text/javascript"></script>
</head>
<body>
<div class="back_head">
    <a class="back" href="<?php echo $backurl; ?>"><img src="<?php echo $tpldir; ?>/images/back.png"></a>
</div>
<!--main-->
<div class="main">
    <!--<h1>color chart</h1>
    <div class="bq"><p>Satin </p><span>Discover our Satin Dress Collection</span></div>-->

    <table id="color-chart">
        <tbody>
        <tr>
            <th colspan="2"><a name="Satin" id="Satin"></a>
                <div>
                    Satin
                    <span>Discover our <a href="/cheap-special-occasion-dresses/69-Satin/">Satin Dress Collection</a></span>
                </div>
            </th>
        </tr>

        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Satin/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="satin">

                </div>
            </td>
        </tr>




        <tr>
            <th colspan="2"><a name="Chiffon" id="Chiffon"></a>
                <div>
                    Chiffon
                    <span>Discover our <a href="/cheap-special-occasion-dresses/69-Chiffon/">Chiffon Dress Collection</a></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Chiffon/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="chiffon">

                </div>
            </td>
        </tr>


        <tr>
            <th colspan="2"><a name="Taffeta" id="Taffeta"></a>
                <div>
                    Taffeta
                    <span> Discover our <a href="/cheap-special-occasion-dresses/69-Taffeta/">Taffeta Dress Collection</a></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/3/BiushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="taffeta">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Organza" id="Organza"></a>
                <div>
                    Organza
                    <span>Discover our <a href="/cheap-special-occasion-dresses/69-Organza/">Organza Dress Collection</a></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Organza/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="organza">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Stretch_Satin" id="Stretch_Satin"></a>
                <div>
                    Stretch Satin
                    <span>Discover our <a href="/cheap-special-occasion-dresses/69-Stretch%20Satin/">Stretch Satin Dress Collection</a></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Strech-Satin/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="elastic_woven_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2">
                <div>
                    <a href="#" name="Charmeuse" id="Charmeuse"></a>Charmeuse
                    <span>Discover our <a href="/cheap-special-occasion-dresses/69-Charmeuse/">Charmeuse Dress Collection</a></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Charmeuse/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="silk_like_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Velet_Chiffon" id="Velet_Chiffon"></a>
                <div>
                    Velvet Chiffon
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/5/BlushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="matte_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Satin_Chiffon" id="Satin_Chiffon"></a>
                <div>
                    Satin Chiffon
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/8/BlushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="Satin_Chiffon_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="30DChiffon" id="30DChiffon"></a>
                <div>
                    30DChiffon
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/30d/33blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="DChiffon">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="warp" id="warp"></a>
                <div>
                    Polyester Warp Knitting
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/warp/18candypink.jpg" alt="" /><span>Candy Pink</span></p></td>
            <td>
                <div id="Polyester_Warp_Knitting">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="weft" id="weft"></a>
                <div>
                    Polyester Weft Knitting
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/weft/9candypink.jpg" alt="" /><span>Candy Pink</span></p></td>
            <td>
                <div id="Polyester_Weft_Knitting">

                </div></td>
        </tr>
        </tbody>
    </table>





</div>
<!--main end-->

</body>
<?php $this->render('parts/after_body.phtml'); ?>
</html>