<?php
  $this->assign('menuItem', 'site_blacklist');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
	<ul>
		<li><span class="basic"><a href="<?php echo url('admin/site/blacklistsetting') ?>">Robots设置</a></span></li>
	</ul>
</div>

<div class="main_right" style="margin-left:10px;margin-top:5px;">
    <?php echo themeMessages() ?>
    <form action="" method="post">
    <table>
      <tr class="nohover"><td class="bold" colspan="2">Robots列表</td></tr>
      <tr>
        <td width="50%">
          <textarea name="robots" rows="20"><?php echo $robots ?></textarea>
        </td>
        <td width="40%">Robots.txt 设置</td>
      </tr>
    </table>
    <div class="main_bottom_deal">
      <input type="submit" value="保存" class="btn">
    </div>
    </form>
  </div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
