<?php
  $this->assign('menuItem', 'site_shipping');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>

<div class="import clear">
  <ul>
    <li><span class="check"><a href="<?php echo url('admin/site/shippingList') ?>"> 配送区域管理</a></span></li>
    <li><span class="basic"><a href="<?php echo url('admin/site/editshippingarea/'.$name);?>">新增配送区域</a></span></li>
  </ul>
</div>

<div class="main_right" style="margin-left:10px;margin-top:5px;">
    <?php echo themeMessages() ?>
    <table>
      <tr class="subhead">
        <td width="5%">ID</td>
        <td width="20%">配送区域</td>
        <td width="50%">配送地区</td>
        <td width="10%">管理</td>
      </tr>
<?php
$i = 1;
  if(isset($config['setting'])):
    foreach($config['setting'] as $k => $v):
?>
      <tr>

        <td><?php echo $k; ?></td>
        <td><?php echo isset($v['areaname'])? $v['areaname'] : NULL; ?></td>
        <td>
<?php
  foreach($v['area'] as $k2 => $v2):
    foreach($v2 as $k3 => $v3):
      echo (isset($countries[$k2]) ? $countries[$k2] : 'all') .' '. (isset($provinces[$v3]) ? $provinces[$v3] : null) . ' ; ' ;
    endforeach;
  endforeach;
?>
        </td>

        <td>
          <a href="<?php echo url('admin/site/editshippingarea/'.$name.'/'.$k); ?>">编辑</a>
          <a href="<?php echo url('admin/site/deleteshippingarea/'.$name.'/'.$k); ?>">删除</a>
        </td>
      </tr>
<?php
    endforeach;
  endif;
?>
    </table>
  </div>

<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
