<?php
  $this->assign('menuItem', 'order_order_mail_setting');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
	<ul>
		<li><span class="basic"><a href="<?php echo url('admin/order/mailsetting')?>">订单邮件设置</a></span></li>
	</ul>
</div>

<div class="main_right" style="margin-left:10px;margin-top:10px;">
    <?php echo themeMessages() ?>
    <form action="" method="POST">

    <table>
      <tr class="nohover"><td class="bold" colspan="2">是否开启订单邮件功能</td></tr>
      <tr>
        <td width="50%">
          <input id="el-c9631-e855c" type="radio" name="orderTradingEmail" value="1" <?php if($orderTradingEmail == 1) echo "checked";  ?>/> <label for="el-c9631-e855c">开启</label>
          <input id="el-c9631-e855b" type="radio" name="orderTradingEmail" value="0" <?php if($orderTradingEmail == 0) echo "checked";  ?>/> <label for="el-c9631-e855b">关闭</label>
        </td>
        <td width="40%"></td>
      </tr>

      <tr class="nohover"><td class="bold" colspan="2">是否开启撤单邮件功能</td></tr>
      <tr>
        <td width="50%">
          <input id="el-c9631-e855e" type="radio" name="orderCancelEmail" value="1" <?php if($orderCancelEmail == 1) echo "checked";  ?>/> <label for="el-c9631-e855e">开启</label>
          <input id="el-c9631-e855f" type="radio" name="orderCancelEmail" value="0" <?php if($orderCancelEmail == 0) echo "checked";  ?>/> <label for="el-c9631-e855f">关闭</label>
        </td>
        <td width="40%"></td>
      </tr>

      <tr class="nohover"><td class="bold" colspan="2">是否开启发货通知邮件功能</td></tr>
      <tr>
        <td width="50%">
          <input id="el-c9631-e855e" type="radio" name="deliverGoodsEmail" value="1" <?php if($deliverGoodsEmail == 1) echo "checked";  ?>/> <label for="el-c9631-e855e">开启</label>
          <input id="el-c9631-e855f" type="radio" name="deliverGoodsEmail" value="0" <?php if($deliverGoodsEmail == 0) echo "checked";  ?>/> <label for="el-c9631-e855f">关闭</label>
        </td>
        <td width="40%"></td>
      </tr>
    </table>

    <div class="main_bottom_deal">
      <input type="submit" value="保存" class="btn">
    </div>
    </form>
  </div>


<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
