<?php
  $this->assign('menuItem', 'order_orderslist');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/order/getList')?>"><?php echo t('Order Manage') ?></a></span></li>
		<li><span class="basic">编辑订单</span></li>
	</ul>
</div>

<div class="main_right tableonhover" style="margin-left:10px;margin-top:10px;">
<?php echo themeMessages() ?>
  <form action="<?php echo url('admin/order/updateorder'); ?>" method="post">
  <input type="hidden" name="goods_amount" id="goods_amount" value = "<?php echo isset($orderInfo->goods_amount) ? $orderInfo->goods_amount : '0'; ?>">
  <input type="hidden" name="goods_number" id="goods_number" value = "<?php echo isset($orderInfo->goods_number) ? $orderInfo->goods_number : '0'; ?>">
  <input type="hidden" name="goods_weight" id="goods_weight" value = "<?php echo isset($orderInfo->goods_weight) ? $orderInfo->goods_weight : '0'; ?>">
  <input type="hidden" name="oid" value="<?php echo $orderInfo->oid;?>">
  <input type="hidden" name="old_status_shipping" value="<?php echo $orderInfo->status_shipping;?>">
  <input type="hidden" name="old_status_payment" value="<?php echo $orderInfo->status_payment;?>">
  <input type="hidden" name="old_shipping_no" value="<?php echo isset($orderInfo->data['shipping_no']) ? $orderInfo->data['shipping_no'] : '' ?>"/>
  <input type="hidden" name="total_amount" value="<?php echo $orderInfo->total_amount;?>">
  <input type="hidden" name="cid" id="cid" value="<?php echo $orderInfo->delivery_cid;?>">
  <input type="hidden" name="pid" id="pid" value="<?php echo $orderInfo->delivery_pid;?>">
      <div class="main_title"><?php echo t('Order Info'); ?></div>
      <table>
        <tr>
          <td width="10%">订单号：</td>
          <td width="30%"><?php echo isset($orderInfo->number) ? $orderInfo->number : ''; ?></td>
          <td width="10%">下单时间：</td>
          <td width="30%"><?php echo isset($orderInfo->created) ? date("Y-m-d H:i:s",$orderInfo->created) : ''; ?></td>
        </tr>
         <tr>
          <td>商品总金额：</td>
          <td><?php echo isset($orderInfo->total_amount) ? $orderInfo->total_amount : ''; ?></td>
          <td>订单总金额：</td>
          <td><?php echo isset($orderInfo->pay_amount) ? $orderInfo->pay_amount : ''; ?></td>
        </tr>
        <tr>
          <td>支付方式：</td>
          <td><?php echo isset($orderInfo->payment_name) ? $orderInfo->payment_name : ''; ?></td>
          <td>商品重量：</td>
          <td><?php echo isset($orderInfo->goods_weight) ? $orderInfo->goods_weight : ''; ?></td>
        </tr>
        <tr>
          <td>订单状态：</td>
          <td><select name="status">
            <option value="0" <?php if($orderInfo->status==0) echo 'selected'; ?>>待处理</option>
            <option value="1" <?php if($orderInfo->status==1) echo 'selected'; ?>>处理中</option>
            <option value="2" <?php if($orderInfo->status==2) echo 'selected'; ?>>完成</option>
            <option value="-1" <?php if($orderInfo->status==-1) echo 'selected'; ?>>撤单</option>
            <option value="-2" <?php if($orderInfo->status==-2) echo 'selected'; ?>>删除</option>
          </select></td>
          <td>支付状态：</td>
          <td><select name="status_payment">
            <option value="0" <?php if($orderInfo->status_payment==0) echo 'selected'; ?>>未支付</option>
            <option value="1" <?php if($orderInfo->status_payment==1) echo 'selected'; ?>>已支付</option>
          </select></td>
        </tr>
        <tr>
          <td>配送状态：</td>
          <td><select name="status_shipping">
            <option value="0" <?php if($orderInfo->status_shipping==0) echo 'selected'; ?>>未配送</option>
            <option value="1" <?php if($orderInfo->status_shipping==1) echo 'selected'; ?>>已配送</option>
          </select></td>
          <td>物流编号：</td>
          <td><input class="mediumtxt" name="shipping_no" id="shipping_no" value="<?php echo isset($orderInfo->data['shipping_no']) ? $orderInfo->data['shipping_no'] : '' ?>"></td>
        </tr>
        <tr>
          <td>配送方式：</td>
          <td>
            <select name="shipping_method" id="shipping_method">
            <?php foreach ($shippingList as $k => $v) : ?>
              <option value="<?php echo $k;?>" <?php if ($orderInfo->shipping_method == $k) echo 'selected';?>><?php echo $v->name;?></option>
            <?php endforeach;?>
            </select>
          </td>
          <td>配送费用：</td>
          <td>
            <input type="hidden" name="fees[shipping][orders_feeid]" value="<?php echo isset($orderInfo->fees['shipping']->orders_feeid) ? $orderInfo->fees['shipping']->orders_feeid : '';?>">
            <input class="mediumtxt" name="fees[shipping][fee_value]" id="shipping_money" value="<?php echo isset($orderInfo->fees['shipping']->fee_value) ? $orderInfo->fees['shipping']->fee_value : '';?>">
          </td>
        </tr>
        <tr>
          <td>IP 来源：</td>
          <td colspan="3">
            <?php echo isset($orderInfo->created_ip) && $orderInfo->created_ip != '0.0.0.0' ? $orderInfo->created_ip : null ?>
          </td>
        </tr>
        <tr>
          <td>备注：</td>
          <td colspan="3">
            <textarea name="data[remark]"><?php echo isset($orderInfo->data['remark']) ? $orderInfo->data['remark'] : null?></textarea>
          </td>
        </tr>
      </table>

      <div class="main_title"><?php echo t('Order OtherInfo'); ?></div>
	    <table>
	      <tr>
	      <td width="10%">折扣或涨价：</td>
          <td width="30%">
          <input type="hidden" name="fees[sales_promotion][orders_feeid]" value="<?php echo isset($orderInfo->fees['sales_promotion']->orders_feeid) ? $orderInfo->fees['sales_promotion']->orders_feeid : '';?>">
          <input class="mediumtxt" name="fees[sales_promotion][fee_value]" value="<?php echo isset($orderInfo->fees['sales_promotion']->fee_value) ? $orderInfo->fees['sales_promotion']->fee_value : '';?>"><0为折扣，>0为涨价</td>
	        <td width="10%">保价：</td>
	        <td width="30%">
	        <input type="hidden" name="fees[support][orders_feeid]" value="<?php echo isset($orderInfo->fees['support']->orders_feeid) ? $orderInfo->fees['support']->orders_feeid : '';?>">
	        <input class="mediumtxt" name="fees[support][fee_value]" value="<?php echo isset($orderInfo->fees['support']->fee_value) ? $orderInfo->fees['support']->fee_value : '';?>"></td>
	      </tr>
	      <tr>
	        <td width="10%">税金：</td>
          <td width="30%">
          <input type="hidden" name="fees[taxes][orders_feeid]" value="<?php echo isset($orderInfo->fees['taxes']->orders_feeid) ? $orderInfo->fees['taxes']->orders_feeid : '';?>">
          <input class="mediumtxt" name="fees[taxes][fee_value]" value="<?php echo isset($orderInfo->fees['taxes']->fee_value) ? $orderInfo->fees['taxes']->fee_value : '';?>"></td>
	        <td>发票抬头：</td>
	        <td>
	        <input class="mediumtxt" name="fees[taxes][description]" value="<?php echo isset($orderInfo->fees['taxes']->description) ? $orderInfo->fees['taxes']->description : '';?>"></td>
	      </tr>
	      <?php if (isset($orderInfo->fees) && $orderInfo->fees) :
	       foreach ($orderInfo->fees as $fee) :
	       if ($fee->fee_type == 0) :
	      ?>
  	      <tr>
            <td width="10%"><?php echo $fee->fee_name?>：</td>
            <td width="30%">
            <input type="hidden" name="fees[<?php echo $fee->fee_key ?>][orders_feeid]" value="<?php echo isset($orderInfo->fees[$fee->fee_key]->orders_feeid) ? $orderInfo->fees[$fee->fee_key]->orders_feeid : ''?>">
            <input class="mediumtxt" name="fees[<?php echo $fee->fee_key ?>][fee_value]" value="<?php echo isset($orderInfo->fees[$fee->fee_key]->fee_value) ? $orderInfo->fees[$fee->fee_key]->fee_value : ''?>"></td>
            <td></td>
            <td></td>
          </tr>
	      <?php
	      endif;
	      endforeach;
	      endif;?>
	    </table>


	    <div class="main_title"><?php echo t('Order BuyMember'); ?></div>
	    <table>
	      <tr>
	        <td width="10%"> 姓名：</td>
	        <td width="30%"><?php echo isset($orderInfo->user->nickname) ? $orderInfo->user->nickname : ''?></td>
	        <td width="10%">会员用户名：</td>
	        <td width="30%"><?php echo isset($orderInfo->user->name) ? $orderInfo->user->name : '' ?></td>
	      </tr>
	      <tr>
	        <td>联系电话：</td>
	        <td><?php echo isset($orderInfo->user->phone) ? $orderInfo->user->phone : ''?></td>
	        <td> Email地址：</td>
	        <td><?php echo isset($orderInfo->user->email) ? $orderInfo->user->email :''?></td>
	      </tr>
	      <tr>
	        <td>地址：</td>
	        <td><?php echo isset($orderInfo->user->area) ? $orderInfo->user->email : ''?></td>
	        <td>邮政编码：</td>
	        <td><?php echo isset($orderInfo->user->postcode) ? $orderInfo->user->postcode :''?></td>
	      </tr>
	    </table>

	    <div class="main_title"><?php echo t('Order ShipMember'); ?></div>
	    <table>
	      <tr>
	        <td width="10%"> 收货人姓：</td>
	        <td width="30%"><input class="mediumtxt non-empty"  title="收货人姓名不能为空" name="delivery_last_name" value="<?php echo isset($orderInfo->delivery_last_name) ? $orderInfo->delivery_last_name : ''; ?>"> <span style="color:red">*</span></td>
	        <td width="10%">收货人名：</td>
	        <td width="30%"><input class="mediumtxt  non-empty"  title="联系手机不能为空" name="delivery_first_name" value="<?php echo isset($orderInfo->delivery_first_name) ? $orderInfo->delivery_first_name : ''; ?>"> <span style="color:red">*</span></td>
	      </tr>
	      <tr>
	        <td>联系电话：</td>
	        <td><input class="mediumtxt" name="delivery_phone" value="<?php echo isset($orderInfo->delivery_phone) ? $orderInfo->delivery_phone : ''; ?>"></td>
	         <td width="10%">联系手机：</td>
          <td width="30%"><input class="mediumtxt" name="delivery_mobile" value="<?php echo isset($orderInfo->delivery_mobile) ? $orderInfo->delivery_mobile : ''; ?>"> <span style="color:red">*</span></td>
	      </tr>
	      <tr>
	        <td> Email地址：</td>
          <td><input class="mediumtxt" name="delivery_email" value="<?php echo isset($orderInfo->delivery_email) ? $orderInfo->delivery_email : ''; ?>"></td>
	        <td>邮政编码：</td>
	        <td><input class="mediumtxt non-empty"  title="邮政编码不能为空" name="delivery_postcode"   value="<?php echo isset($orderInfo->delivery_postcode) ? $orderInfo->delivery_postcode : ''; ?>"> <span style="color:red">*</span></td>
	      </tr>


	       <tr>

            <td>送货时间：</td>
          <td><input class="mediumtxt" name="delivery_time" value="<?php echo isset($orderInfo->delivery_time) ? $orderInfo->delivery_time : ''; ?>"></td>
            <td>城市：</td>
            <td><input class="general_text non-empty"  title="Receiving city can't for empty" id="delivery_city" name="delivery_city" value="<?php echo isset($orderInfo->delivery_city) ? $orderInfo->delivery_city : ''; ?>"> <font color="red">*</font></td>
        </tr>

         <tr>
          <td>国家：</td>
          <td><?php echo isset($orderInfo->delivery_country) ? $orderInfo->delivery_country : ''; ?>
                  <!--<select  id="select_countries" name ="delivery_cid" class="general_select non-empty" title="Country can not for empty" disabled>
<?php foreach($countries as $k => $v) : ?>
        <option value="<?php echo $k ?>"><?php echo $v ?></option>
<?php endforeach;?>
        </select>  <font color="red">*</font>
          --></td>
          <td>省份：</td>
          <td>
          <?php echo isset($orderInfo->delivery_province) ? $orderInfo->delivery_province : ''; ?>
        <!--<select  id="select_provinces" name ="delivery_pid" class="general_select" disabled>
        <option value="0"></option>
<?php foreach($provinces as $k => $v) : ?>
        <option value="<?php echo $k ?>"><?php echo $v ?></option>
<?php endforeach;?>
        </select>
--></td>

        </tr>

	      <tr>
	        <td>收货地址：</td>
	        <td colspan="3"><input class="txt non-empty"  title="收货地址不能为空"  name="delivery_address" value="<?php echo isset($orderInfo->delivery_address) ? $orderInfo->delivery_address : ''; ?>"> <span style="color:red">*</span></td>
	      </tr>
	    </table>

	     <div class="main_title">商品清单</div>
      <table class="td-overflow-visible">
        <tr>
          <td width="10%"></td>
          <td width="10%">ID</td>
          <td width="25%">商品名称</td>
          <td width="20%">属性</td>
          <td width="8%">价格</td>
          <td width="8%">购买数量</td>
          <td width="8%">小计</td>
          <td width="5%">管理</td>
        </tr>

<?php
if(isset($orderInfo->items)):
  foreach($orderInfo->items as $key => $dl):
?>
        <tr>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><img src="<?php echo urlimg('admin_product_album', $dl->filepath) ?>"></a></td>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><?php echo $dl->number?><input type="hidden" name="oiid[]" value="<?php echo $dl->oiid?>"></a></td>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><?php echo $dl->name?></a></td>
          <td>
          <?php if (!empty($dl->data)){echoOrderItemProperties($dl->data);}?>
          </td>
          <td><input name="item_pay_price[]" class="littletxt" value="<?php echo $dl->pay_price?>" size="6" /></td>
          <td><input name="item_number[]" class="littletxt" value="<?php echo $dl->qty?>" size="4" /></td>
          <td><?php echo $dl->total_amount?></td>
          <td><a href="<?php echo url('admin/order/deleteOrderItem/'.$orderInfo->oid.'/'.$dl->oiid);?>"  class="btn_confirm" rel="确认删除该商品吗?">删除</a></td>
        </tr>
<?php
  endforeach;
endif;
?>
        <tr><td colspan="7"  class="div_btn_bottom" style="height:40px;">货号：<input class="littletxt" name="new_pid" />
        <input type="submit" name="addOrderItem" class="btn" value="添加" title="nocheck"></td></tr>
      </table>

	    <div class="div_btn_bottom">
	      <input class="btn" type="submit" name="edit" value="<?php echo t('Save'); ?>">
        <input type="button" value="取消" class="Buttom_4 btn btn_cancel"/>
	    </div>
    </form>
  </div>


<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>

