<?php
  echo $this->render('admin/before_body.phtml');
  if ($orderInfo->items) {
    foreach ($orderInfo->items as $k => $v) {
      $orderInfo->total_num += $v->qty;
    }
  }
?>

  <link rel="stylesheet" type="text/css" href="<?php echo url('styles/print.css') ?>" media="print" />
<style>
  .pritf22 td{border:1px solid #E0E0E0;}
  .notopborder td{border-top:0px;}
</style>
  <div class="main_right main_right_iframe tableonhover" style="height:auto">
  <div style="width:800px;margin:0px auto;" class="pritf22">
  <br>
  <h1 style="text-align:center;">订单信息</h1>
  <br>
    <table width="90%" class="nohover">
      <tr>
        <td colspan="3">订单编号 : <?php echo isset($orderInfo->number) ? $orderInfo->number : ''; ?></td>
        <td colspan="3">付款方式 : <?php echo isset($orderInfo->payment_method) ? $orderInfo->payment_method : ''; ?></td>
      </tr>
      <tr>
        <td colspan="6">收货人  ： <?php echo isset($orderInfo->delivery_first_name) ? $orderInfo->delivery_first_name : ''; ?> <?php echo isset($orderInfo->delivery_last_name) ? $orderInfo->delivery_last_name : ''; ?></td>
      </tr>
      <tr>
        <td rowspan="2" width="80" style="width:80px">收货人<br>详细地址：</td>
        <td>地址</td>
        <td>城市</td>
        <td>省份</td>
        <td>邮编</td>
        <td>国家</td>
      </tr>
      <tr>
        <td><?php echo isset($orderInfo->delivery_address) ? $orderInfo->delivery_address : ''; ?></td>
        <td><?php echo isset($orderInfo->delivery_city) ? $orderInfo->delivery_city : ''; ?></td>
        <td><?php echo isset($orderInfo->delivery_province) ? $orderInfo->delivery_province : ''; ?></td>
        <td><?php echo isset($orderInfo->delivery_postcode) ? $orderInfo->delivery_postcode : ''; ?></td>
        <td><?php echo isset($orderInfo->delivery_country) ? $orderInfo->delivery_country : ''; ?></td>
      </tr>
      <tr>
        <td colspan="6">电话： <?php echo isset($orderInfo->delivery_mobile) ? $orderInfo->delivery_mobile : ''; ?></td>
      </tr>
      <tr>
        <td colspan="6">邮箱  ： <?php echo isset($orderInfo->delivery_email) ? $orderInfo->delivery_email : ''; ?></td>
      </tr>
    </table>

    <table>
<tr class="notopborder">
          <td width="10%">编号</td>
          <td width="10%">图片</td>
          <td width="25%">商品名称</td>
          <td width="20%">属性</td>
          <td width="8%">购买数量</td>
          <td width="8%">价格</td>
          <td width="8%">小计</td>
        </tr>

<?php
if(isset($orderInfo->items)):
  foreach($orderInfo->items as $key => $dl):
?>
        <tr>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><?php echo $dl->sn?><input type="hidden" name="oiid[]" value="<?php echo $dl->oiid?>"></a></td>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><img src="<?php echo urlimg('admin_product_album', $dl->filepath) ?>"></a></td>
          <td><a href="<?php echo url($dl->url) ?>" target="_blank"><?php echo $dl->name?></a></td>
          <td>
           <?php if (!empty($dl->data)){echoOrderItemProperties($dl->data);}?>
          </td>
          <td><?php echo $dl->qty?></td>
          <td><?php echo c($dl->pay_price)?></td>
          <td><?php echo c($dl->total_amount)?></td>
        </tr>
<?php
  endforeach;
endif;
?>
      <tr>
        
        <td colspan="7" style="text-align:right;">
        商品总数：<?php echo isset($orderInfo->total_num) ? $orderInfo->total_num : ''; ?><br>     
        商品总价：<?php echo isset($orderInfo->total_amount) ? c($orderInfo->total_amount) : ''; ?><br>
          <?php
          if (isset($orderInfo->fees)) :
            foreach ($orderInfo->fees as $fee) :
              if ($fee->fee_value) :
                echo t($fee->fee_name) . ' : ' . c($fee->fee_value) . '<br>';
              endif;
            endforeach;
          endif;?>
     应付款金额：<?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : 0?><br>
        </td>
         
      </tr>
    </table>
    <div class="noprint center">
      <input class="btn" type="button" value="打印" onclick="window.print();">
    </div>
    </div>
  </div>
  

<?php
  echo $this->render('admin/after_body.phtml');
?>