<?php global $basePath ?>
<script type="text/javascript">
var basePath = '<?php echo plain($basePath) ?>';
</script>
<script type="text/javascript" src="<?php echo url('scripts/jquery-1.4.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo url('scripts/jquery-ui-1.8.3.min.js') ?>"></script>
<?php echo $scripts ?>
<script type="text/javascript" src="<?php echo url('scripts/admin.js?v4');?>" ></script>
</html>
