<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php if (isset($docTitle)) echo plain($docTitle) ?></title>
<?php if (isset($docDescription)): ?>
<meta name="description" content="<?php echo plain($docDescription) ?>" />
<?php endif ?>
<?php if (isset($docKeywords)): ?>
<meta name="keywords" content="<?php echo plain($docKeywords) ?>" />
<?php endif ?>
<link rel="stylesheet" type="text/css" href="<?php echo url('styles/global.css') ?>" />
<?php echo $styles ?>
<link rel="stylesheet" type="text/css" href="<?php echo url('images/admin/style.css') ?>" />
</head>
