<?php echo $this->render('admin/before_body.phtml', array('docTitle' => '后台管理登录', )) ?>


<link href="<?php echo url('images/admin/home.css') ?>" rel="stylesheet" type="text/css" />

<body>
  <div class="wrapper">
  <div class="google-header-bar">
  
<div class="header content clearfix">
  <h1 style="font-family: arial;font-size: 40px;padding-top: 20px;color: #777777;">Admin Console</h1>
  </div>
  </div>
  <div class="main content clearfix">

<div class="sign-in">


<div class="signin-box">

<?php echo themeMessages() ?>

  <h2>Log In</h2>
  <form id="gaia_loginform" action="" method="post">
  <div class="email-div">
	  <label for="username"><strong class="email-label">User Name</strong></label>
	  <input type="text" class="bltext" value=""  name="username"/>
  </div>
<div class="passwd-div">
  <label for="Passwd"><strong class="passwd-label">Password</strong></label>
  <input type="password" class="bltext" value=""  name="password"/>
</div>
  <input type="submit" class="g-button g-button-submit" name="signIn" id="signIn"
      value="submit">
  </form>

</div>
  </div>

  </div>

  </div>

</body>




<?php echo $this->render('admin/after_body.phtml') ?>
