<?php
  $this->assign('menuItem', 'product_typelist');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>
<div class="import clear">
    <ul>
        <li><span class="check"><a href="<?php echo url('admin/filtergroup/getlist') ?>">过滤选项组管理</a></span></li>
        <li><span class="check"><a href="<?php echo url('admin/filtergroup/fieldlist/' . $groupId) ?>">过滤选项组编辑</a></span></li>
        <li><span class="check">更新过滤选项</span></li>
    </ul>
</div>

<div class="main_right">
    <?php echo themeMessages(); ?>
    <?php echo $this->render('admin/filtergroup/filterfieldform.phtml'); ?>
    <table>
       <tr class="noborder nohover" style="border-bottom:0px solid red;">
        <td colspan="2">
          <input type="button" id="edit_filter_field_btn" value="提交" class="Buttom_3 but" />
          <a href="<?php echo url('admin/filtergroup/fieldlist/' .  $groupId) ?>" class="Buttom_4b">返回列表</a>
        </td>
      </tr>
    </table>
</div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
