<?php
  $this->assign('menuItem', 'product_vocabulary');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>

<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/filtergroup/getList'); ?>">查看过滤选项组</a></span></li>
		<?php if (access('edit filtergroup')): ?>
		<li><span class="new"><a href="<?php echo url('admin/filtergroup/insert/'); ?>">新建过滤选项组</a></span></li>
		<?php endif; ?>
	</ul>
</div>
<div class="main_right">
    <?php echo themeMessages() ?>
    <table>
        <tr class="subhead">
            <td width="10%">编号</td>
            <td width="35%">过滤选项组名称</td>
            <td width="55%"><?php if (access( array('list filtergroup', 'edit filtergroup', 'delete filtergroup', ), 'or')): ?>管理<?php endif; ?></td>
        </tr>
        <?php
        if (isset($filterGroupList)):
        foreach($filterGroupList as $key => $value):
        ?>
        <tr>
            <td><?php echo $key; ?></td>
            <td>
                <?php if (access('edit filtergroup')): ?>
                    <a href="<?php echo url('admin/filtergroup/fieldlist/' . $value->id); ?>">
                <?php endif; ?>
                <?php echo $value->name; ?>
                <?php if (access('edit filtergroup')): ?></a><?php endif; ?>
            </td>
            <td>
                <?php if (access('edit filtergroup')): ?><a href="<?php echo url('admin/filtergroup/fieldlist/' . $value->id); ?>">编辑选项</a><?php endif; ?>
                <?php if (access('edit filtergroup')): ?><a href="<?php echo url('admin/filtergroup/edit/' . $value->id); ?>">修改名称</a><?php endif; ?>
                <?php if (access('delete filtergroup')): ?>
                <a href="<?php echo url('admin/filtergroup/delete/' . $value->id) ?>" class="btn_confirm" rel="确认删除该过滤选项组吗?">删除</a>
                <?php endif; ?>
            </td>
        </tr>
        <?php
        endforeach;
        endif;
        ?>
        <?php if (access('list filtergroup')): ?>
        <tr>
            <td colspan="4">
                <a href="<?php echo url('admin/filtergroup/insert/'); ?>">新建选项组</a>
            </td>
        </tr>
        <?php endif; ?>
    </table>
</div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
