<a class="todo-list" href="<?php echo url("product/topmenu"); ?>" ><img src="<?php echo themeResourceURI('images/top-list.png') ?>"/></a>
<a class="top-logo" href="/" ><img src="<?php echo themeResourceURI('images/top-logo.png') ?>" /></a>
<a class="top-car" href="<?php echo url("user/myaccount"); ?>" ><img src="<?php echo themeResourceURI('/images/top-person.png') ?>"/></a>
<a class="top-person" href="<?php echo url('cart'); ?>" ><img src="<?php echo themeResourceURI('/images/top-char.png'); ?>"/></a>
<div class="clear"></div>