<?php
  $this->assign('menuItem', 'user_mailsetting');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>

<div class="import clear">
	<ul>
		<li><span class="basic"><a href="<?php echo url('admin/user/mailsetting') ?>">用户邮件设置</a></span></li>
	</ul>
</div>

<div class="main_right" style="margin-top:10px;margin-left:5px;margin-bottom:20px;">
    <?php echo themeMessages() ?>
    <form action="" method="POST">

    <table>
      <tr class="nohover"><td class="bold" colspan="2">是否开启注册用户邮件功能</td></tr>
      <tr>
        <td width="50%">
          <input id="el-c9631-e855c" type="radio" name="status" value="1" <?php if($userRegisterEmail['status'] == 1) echo "checked";  ?>/> <label for="el-c9631-e855c">开启</label>
          <input id="el-c9631-e855b" type="radio" name="status" value="0" <?php if($userRegisterEmail['status'] == 0) echo "checked";  ?>/> <label for="el-c9631-e855b">关闭</label>
        </td>
        <td width="40%"></td>
      </tr>
      <tr class="nohover"><td class="bold" colspan="2">邮件标题</td></tr>
      <tr>
        <td width="50%">
          <input type="text" name="title" class="txt" value="<?php echo $userRegisterEmail['title']?>" />
        </td>
        <td width="40%"></td>
      </tr>
      <tr class="nohover"><td class="bold" colspan="2">内容格式</td></tr>
      <tr>
        <td width="50%">
          <input id="el-c9631-e855e" type="radio" name="type" value="1" <?php if($userRegisterEmail['type'] == 1) echo "checked";  ?>/> <label for="el-c9631-e855e">html</label>
          <input id="el-c9631-e855f" type="radio" name="type" value="0" <?php if($userRegisterEmail['type'] == 0) echo "checked";  ?>/> <label for="el-c9631-e855f">txt</label>
        </td>
        <td width="40%"></td>
      </tr>
      <tr class="nohover"><td class="bold" colspan="2">邮件内容</td></tr>
      <tr>
        <td colspan="2"><textarea name="content" class="xheditor" rows="10"><?php if (isset($userRegisterEmail)) echo plain($userRegisterEmail['content']) ?></textarea></td>
      </tr>
    </table>

    <div class="main_bottom_deal">
      <input type="submit" value="保存" class="btn">
    </div>
    </form>
  </div>


<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
