<?php
  $this->assign('menuItem', 'user_roles');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>

<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/user/roles') ?>">角色管理</a></span></li>
		<li><span class="basic">角色管理 - <?php echo $isnew ? t('New') : plain($role->name) ?></span></li>
	</ul>
</div>

<div class="main_right" style="margin-top:10px;margin-left:10px;">
    <?php echo themeMessages() ?>
    <form action="" method="post">
    <table>
      <tr class="nohover"><td class="bold" colspan="2">角色名称</td></tr>
      <tr>
        <td width="50%"><input name="name" value="<?php if (isset($role)) echo plain($role->name) ?>" class="txt" /></td>
        <td width="45%">角色名称</td>
      </tr>
      <tr class="noborder nohover" style="border-bottom:0px solid red;">
        <td colspan="2">
          <input type="submit" value="提交" class="but" />
          <a href="<?php echo url('admin/user/roles') ?>" class="Buttom_4b">返回列表</a>
        </td>
      </tr>
    </table>
    </form>
  </div>
<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
