<?php foreach($comments as $v): ?>
	<?php $info = widgetCallFunction('fivestars', 'getcommentstarsGrade', $v->cid); ?>
	<?php $grade = $info->grade; ?>
	<div class="latest_review">
		<div>
			<p>By <?php echo strwidth($v->nickname, 17); ?></p>
			<span class="review_star">
				<?php for($i = 0; $i < floor($grade); $i++ ): ?>
					<a><img src="<?php echo $tpldir; ?>/images/starfill.png" /></a>
				<?php endfor; ?>
				<?php if((ceil($grade) - floor($grade)) == 1): ?>
					<a><img src="<?php echo $tpldir; ?>/images/starhalf.png" /></a>
				<?php endif; ?>
				<?php for($i = 0; $i < 5 - ceil($grade); $i++): ?>
					<a><img src="<?php echo $tpldir; ?>/images/star.png" /></a>
				<?php endfor; ?>
				<div class="clear"></div>
			</span>
			<p class="title">
				<span>Title:</span>
				<?php echo $v->subject; ?>
			</p>
			<p class="content">
				<span>Content:</span>
				<?php echo $v->comment; ?>
			</p>
		</div>
		<?php if(!empty($v->photo_paths)): ?>
			<div class="show">
				<?php $isfirst = true; ?>
				<?php foreach($v->photo_paths as $pic): ?>
					<div class="showimg" <?php if($isfirst){echo 'style="margin-left: 0"';} ?>>
						<a href="<?php echo urlimg('water_mark', $pic); ?>"><img src="<?php echo urlimg("85x85", $pic); ?>" /></a>
					</div>
					<?php $isfirst = false; ?>
				<?php endforeach; ?>
				<div class="clear"></div>
			</div>
		<?php endif; ?>
		<span class="date"><?php echo date('M d, Y', $v->timestamp); ?></span>
	</div>
<?php endforeach; ?>