<?php
  $this->assign('menuItem', 'product_vocabulary');
  echo $this->render('admin/before_body.phtml');
  echo $this->render('admin/header.phtml');
?>

<div class="import clear">
	<ul>
		<li><span class="check"><a href="<?php echo url('admin/vocabulary/getList'); ?>">查看商品分类</a></span></li>
		<?php if (access('edit vocabulary')): ?>
		<li><span class="new"><a href="<?php echo url('admin/vocabulary/insert/'); ?>">新建分类</a></span></li>
		<?php endif; ?>
	</ul>
</div>

<div class="shelves" style="display: none">
  <span><strong>当前过滤条件(清除)</strong></span>
  <span>上架:<strong>是</strong></span>
  <a href="#"><img src="<?php echo url('images/admin_new/delete.gif');?>" alt="" /></a>
  <span>库存大于:<strong>1</strong></span>
  <a href="#"><img src="<?php echo url('images/admin_new/delete.gif');?>" alt="" /></a>
</div>


  <div class="main_right">
    <?php echo themeMessages() ?>
    <table>
      <tr class="subhead">
        <td width="8%">编号</td>
        <td width="35%">分类名称</td>
        <td width="20%">分类词数量</td>
        <td width="30%"><?php if (access( array('edit vocabulary', 'list term', 'edit term', 'delete vocabulary', ), 'or')): ?>管理<?php endif; ?></td>
      </tr>
<?php
  if(is_array($vocabularyList)):
    foreach($vocabularyList as $key => $dl):
?>
      <tr>
        <td><?php echo $key+1; ?></td>
        <td><?php if (access('edit vocabulary')): ?><a href="<?php echo url('admin/vocabulary/getInfo/' . $dl->vid); ?>"><?php endif; ?>
        <?php echo $dl->name . (trim($dl->name_cn) !== '' ? (' (' . plain(trim($dl->name_cn)) . ')') : '') ?>
        <?php if (access('edit vocabulary')): ?></a><?php endif; ?></td>
        <td><?php echo $dl->count; ?></td>
        <td>
          <?php if (access('edit vocabulary')): ?><a href="<?php echo url('admin/vocabulary/getInfo/' . $dl->vid); ?>">编辑</a><?php endif; ?>
<?php if ($dl->type==0):?>
          <?php if (access('delete vocabulary')): ?>
          <a href="<?php echo url('admin/vocabulary/delete/' . $dl->vid) ?>" class="btn_confirm" rel="确认删除该分类及其分类词吗?">删除</a>
          <?php endif; ?>
          <?php if (access('list term')): ?><a href="<?php echo url('admin/terms/getList/' . $dl->vid); ?>">查看分类词</a><?php endif; ?>
          <?php if (access('edit term')): ?><a href="<?php echo url('admin/terms/getInfo/'.$dl->vid.'/0'); ?>">新增分类词</a><?php endif; ?>
<?php
      else:
        if ($dl->type==1):
?>
           <?php if (access('list term')): ?><a href="<?php echo url('admin/terms/getList/' . $dl->vid); ?>">查看分类词</a><?php endif; ?>
           <?php if (access('edit term')): ?><a href="<?php echo url('admin/terms/getInfo/'.$dl->vid.'/0'); ?>">新增分类词</a><?php endif; ?>
<?php
        else:
?>
           <?php if (access('list term')): ?><a href="<?php echo url('admin/terms/getList/' . $dl->vid); ?>">查看分类词</a><?php endif; ?>
           <?php if (access('edit term')): ?><a href="<?php echo url('admin/terms/getInfo/'.$dl->vid.'/0'); ?>">新增分类词</a><?php endif; ?>
<?php
        endif;
      endif;
?>
</td>
      </tr>
<?php
    endforeach;
  endif;
?>
    </table>
  </div>

<?php
  echo $this->render('admin/footer.phtml');
  echo $this->render('admin/after_body.phtml');
?>
