    <div class="about_us" style="font:1.2rem/2rem 'arial';padding:0 4.5%;margin-top:5px;">
        Appear as a veritable angel to bemuse
        your fiance wearing this marvelous 
        wedding gown. Scoop neckline 
        cap-sleeved bodice comfortably 
        cinches your body. A-line slightly 
        ruched satin skirt dramatically 
        expands contrasting your slender 
        waist and finishes with a gorgeous 
        chapel train behind. Two lines of the 
        silvery embroidered ribbons adorn the 
        bodice crisscrossed upon the 
        enticingly open back.
    </div>