<p class="shir">
We understand that it is not easy to pick the perfect dress for your special day, and sometimes you might change your mind. However, all our orders, either customized items or standard items, are all made-to-order items. Once the tailoring has begun, the material cannot be recycled. The good news is that after placing your order, there is still time to change your mind. Please refer to our cancellation policy below for details.
</p>
<h1>Our Policy</h1>
<h2>1. Unpaid orders</h2>
<p class="shir">
All the unpaid orders would be cancelled automatically 30 days after you place the order. 
</p>
<h2>2. Paid orders</h2>
<table cellspacing="0" cellpadding="0" class="biaoge">
              <tbody>
                
               <tr>
                   <td class="dan">
                     <p align="center">Cancelled within 12 hours of payment confirmation </p>
                   </td>
               </tr>
               <tr>
                   <td>
                      <div class="prod">Product purchase price <br />Shipping cost</div>
                      <div class="perc">100%<br />100%</div>
                      <div class="clear"></div>
                   </td>
               </tr>
               <tr>
                   <td class="dan">
                     <p align="center">Cancelled within 12 to 24 hours of payment confirmation</p>
                   </td>
               </tr>
               <tr>
                   <td>
                      <div class="prod">Product purchase price <br />Shipping cost</div>
                      <div class="perc">80%<br />100%</div>
                      <div class="clear"></div>
                   </td>
               </tr>
               <tr>
                   <td class="dan">
                     <p align="center">Cancelled within 24 to 72 hours of payment confirmation</p>
                   </td>
               </tr>
               <tr>
                   <td>
                      <div class="prod">Product purchase price <br />Shipping cost</div>
                      <div class="perc">70%<br />100%</div>
                      <div class="clear"></div>
                   </td>
               </tr>
               <tr>
                   <td class="dan">
                     <p align="center">Cancelled 72 hours after payment confirmation</p>
                   </td>
               </tr>
               <tr>
                   <td>
                      <div class="prod">Product purchase price <br />Shipping cost</div>
                      <div class="perc">50%<br />100%</div>
                      <div class="clear"></div>
                   </td>
               </tr>
            </tbody>
         </table>
<p class="shir">
* Once the order has been shipped, it cannot be cancelled.
</p>
<h1>How to Cancel a Paid Order?</h1>
<p class="shir">
Please send your cancellation request with order ID to our customer service by email or ticket. Your request would be addressed as soon as possible and according to the above time frame which is based on the arrival of your email or ticket.
</p>