    <table id="color-chart">
        <tbody>
        <tr>
            <th colspan="2"><a name="Satin" id="Satin"></a>
                <div>
                    Satin
                </div>
            </th>
        </tr>

        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Satin/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="satin">

                </div>
            </td>
        </tr>




        <tr>
            <th colspan="2"><a name="Chiffon" id="Chiffon"></a>
                <div>
                    Chiffon

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Chiffon/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="chiffon">

                </div>
            </td>
        </tr>


        <tr>
            <th colspan="2"><a name="Taffeta" id="Taffeta"></a>
                <div>
                    Taffeta

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/3/BiushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="taffeta">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Organza" id="Organza"></a>
                <div>
                    Organza

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Organza/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="organza">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Stretch_Satin" id="Stretch_Satin"></a>
                <div>
                    Stretch Satin

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Strech-Satin/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="elastic_woven_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2">
                <div>
                    <a href="#" name="Charmeuse" id="Charmeuse"></a>Charmeuse

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/Charmeuse/blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="silk_like_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Velet_Chiffon" id="Velet_Chiffon"></a>
                <div>
                    Velvet Chiffon

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/5/BlushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="matte_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="Satin_Chiffon" id="Satin_Chiffon"></a>
                <div>
                    Satin Chiffon
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201209/49918/8/BlushingPink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="Satin_Chiffon_satin">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="30DChiffon" id="30DChiffon"></a>
                <div>
                    30DChiffon
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/30d/33blushingpink.jpg" alt="" /><span>Blushing Pink</span></p></td>
            <td>
                <div id="DChiffon">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="warp" id="warp"></a>
                <div>
                    Polyester Warp Knitting
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/warp/18candypink.jpg" alt="" /><span>Candy Pink</span></p></td>
            <td>
                <div id="Polyester_Warp_Knitting">

                </div></td>
        </tr>
        <tr>
            <th colspan="2"><a name="weft" id="weft"></a>
                <div>
                    Polyester Weft Knitting
                    <span></span>

                </div></th>
        </tr>
        <tr>
            <td width="28%"><p align="center"><img src="<?php echo $tpldir; ?>/images/color_chart/201311/65931/weft/9candypink.jpg" alt="" /><span>Candy Pink</span></p></td>
            <td>
                <div id="Polyester_Weft_Knitting">

                </div></td>
        </tr>
        </tbody>
    </table>
    <script src="<?php echo $tpldir; ?>/javascripts/color-chart-gaitupian.js" type="text/javascript"></script>