<li class="grp-item">
    <a href="/article/about-us.html" class="title aaa">About Us</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/our-guarantee.html" class="title">Our Guarantee</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/contact-us.html" class="title">Contact Us</a>
    <span class="p-arrow"></span>
</li>