<p class="shir">   
            We believe in exceptional customer service, and will do our best to address your needs as quickly as possible. If you have any questions or concerns, please don't hesitate to contact us via Email. 
If your question is about an order you've placed with us, please tell us your order number so that we may better serve you. 
          </p>
          <h1>E-MAIL</h1>
          <p class="email">
            <a href="mailto:support@adoringdress.com">support@adoringdress.com</a>
          </p>
          