<li class="grp-item">
    <a href="/article/size-chart.html" class="title aaa">Size Chart</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/color-chart.html" class="title aaa">Color Chart</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/faq.html" class="title aaa">FAQ</a>
    <span class="p-arrow"></span>
</li>