<br />
<h2>Have questions about us?</h2>
         <p class="shir" style="text-indent:0">
           1 Where are you located?<br />
          We are located in Beijing, China.<br />
          2 Do you have a phone number that I can call? How can I contact you?<br />
          Our Phone number is: +1 (209)759 4078
          Office Time: 9:00am - 6:00pm, Monday to Friday (UTC+08:00).Please note the time difference.
          You can also email us at : <a href="mailto:support@adoringdress.com">support@adoringdress.com</a> , our customer service representatives respond to the emails every week day.
You can also send us tickets by click Customer Service at the top right of the page, and our customer service representatives would respond to that in 24 hours (on week days).<br />
          3 Are you an online bridal store only? Do you have any store in XXX (any city)?<br />
          We are currently doing online sales only, and we don't have physical stores.
         </p><br />
         <h2>Have concerns before your order?</h2>
         <p class="shir" style="text-indent:0">
            1 Can I see a swatch of the color I'm interested in before I order?<br />
        You can order fabric samples here: http://www.adoringdress.com/fabric-samples-pEX_00001.html
        The sample is free, and you are only responsible for the shipping cost.
        And you can get 5 color samples (5 pieces of fabrics) at most once.<br />
        2 What if I want a dress in a color that is not listed?<br />
        If you want a dress in a color that is not listed, you can contact our customer service and send us some pictures of the color you would like, and we'll make the dress in that color.<br />
        3 Can you change the back style of the dresses for me? What if I would like the dress shorter? I want a longer train, is that possible?<br />
        If you want to make changes to our dresses, just contact our customer service about this.
        And we can make changes for you, just note that all customized items without quality issues cannot to be exchanged or returned.<br />
        4 Can I see a picture of the dress itself?<br />
        If you want to see a picture of the dress itself, instead of on a model, you can contact our customer service and ask for the picture.<br />
        5 Will the dress be very similar with what the pictures show?<br />
        The pictures we have displayed on our site feature dresses that fit the sizes mentioned in them. When you order from the catalogue, 
        we tailor the dresses, so they are more than 90% similar to the dresses featured in the pictures.<br />
        6 How far in advance should I order a dress before wedding?<br />
        Since it takes about 13~20 days to make and ship the dress, we would recommend you order the dress 30 days before the wedding, in case you want to make alternations.
         </p><br />
         <h2>Have difficulty in ordering?</h2>
         <p class="shir" style="text-indent:0">
            1 Where are you shipping from?<br />
          Make sure you have chosen both size and color before you hit the "add to cart" button.?<br />
          2 It won't take my card.<br />
          Currently we accept credit card only.
          If you are paying with a debit card, you can choose to pay by PayPal, and through PayPal, you can pay with your debit card.
          And PayPal is highly recommended by us, since it's much easier and safer.<br />
          3 How to pay using a debit card via PayPal?<br />
          a) Select the payment method "PayPal," and then, you'll be transfer to the PayPal payment page<br />
          b) There, click "Don't have a PayPal account?"<br />
          c) You can then pay with your debit card as a PayPal guest<br />
         </p>
         <h2>Have questions about shipping?</h2>
         <p class="shir" style="text-indent:0">
           1 Where are you shipping from?<br />
        All our dresses are shipping from China.<br />
        2 Where can you ship to?<br />
        We ship worldwide, and we would contact you if we could not ship to your address. So remember to leave correct contact information when place the order.<br />
        3 How long does it take to ship?<br />
        a) Expedited Shipping<br />
        This shipping method is the fastest available. Delivery times are between 3-5 days to all major destinations.<br />
        b) Standard Shipping<br />
        Standard shipping takes a bit longer than expedited shipping but costs less. Delivery times are between 6-8 days to all major destinations.<br />
        4 How much is the shipping cost?<br />
        Shipping fee is calculated based on the weight of your order.
        And it varies when the destination changes. If you want to know the shipping cost before ordering, you can contact our customer service to find out.<br />
        5 What courier company are you using?<br />
        We usually use reputed companies like UPS, DHL and EMS, etc.<br />
        6 How long does it take to get my package? When will I get my dress?<br />
        The shipping itself would take about 3~5 days (Expedited Shipping), and it takes about 15~20 days to tailor the dress, so you'll get the dress in 15~ 23 days.
        </p><br />
        <h2>Have questions about payment?</h2>
        <p class="shir" style="text-indent:0">
           1 What payment methods do you currently accept?<br />
        You may pay by either of the following methods:<br />
        a) Credit Card<br />
        You may pay by credit card, but please note that your final payment might differ from your order price.<br />
        b) PayPal<br />
        You may also pay by PayPal.
        If you happen to have no PayPal account, you may still choose to pay by PayPal when you checkout, 
        and you would be directed to a PayPal page where you would follow the instructions to sign up for a PayPal account.
        You can also choose to pay by a debit or credit card, or Bill Me Later on the PayPal page<br />
        2 Why didn't the payment go through?<br />
        If the payment did not go through, it's probably because that you bank has declined the transaction. And you can contact your bank to get a permit for this transaction.<br />
        3 I was charged more than the price on the website.<br />
        If you are paying by credit card, your final payment might differ from your order price, which may be due to either or both of the following situations:<br />
        1) Exchange rates difference between your bank and our bank<br />
        We are using Globe Bill to process credit card transactions. Globe Bill would first exchange the order price to RMB (Chinese Currency), using our exchange rates. 
        When charging your credit card, your bank would have to exchange RMB into your currency, using their exchange rates. Therefore, 
        if your bank's exchange rate differs from that of ours, the final charge would vary from the order price. Usually the variation would be within 3% to 5% of your total payment.<br />
        2) Transaction fees<br />
        Your bank might charge you for a transaction fee, which varies from 0.5-8 US Dollars. Please note, this fee would not be included in our refund.
        </p>
        <h2>Have questions about your orders?</h2>
        <p class="shir" style="text-indent:0">
          1 Where I can get the tracking information?<br />
        After your order is shipped, you'll get a confirmation email, including the tracking number.<br />
        2 How can I check my order status?<br />
        Log in your account, and click "view my order" on the top right of the page, you will see a list of your order. And by clicking at an order number, 
        you can see the detail information of you order, including "order status".
        And you can also contact our customer service to check your order status, our representatives would be happy to help you.<br />
        3 Can I change the size or color for my dresses after payment?<br />
        Once the tailoring started, it's no longer possible to make any changes. So if you want to change the size or color, contact the customer service. 
        Even it's too late to make the change, our representatives would work out a way to help you.
        </p><br />
        <h2>Have questions about Return and Exchange?</h2>
        <p class="shir" style="text-indent:0">
           1 Can I exchange an item?<br />
        Yes, you can. Contact our customer service and our representatives would advise. You would be responsible for all the shipping cost, if there is no quality issue.<br />
        2 What's your Return Policy?<br />
        Please check our Return Policy here: http://www.adoringdress.com/article/return-policy.html<br />
        3 Can I return a personalized item?<br />
        Personalized items/custom orders with no quality issues cannot be returned or exchanged.
        </p> 