<p class="shir">   
            You may pay by either of the following methods:
          </p>
          <h2>Credit Card</h2>
          <p class="shir">
           You may pay by credit card, but please note that your final payment might differ from your order price, which may be due to either or both of the following situations:<br /><br />
           1. Exchange rates difference between your bank and our bank<br />
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We are using Globe Bill to process credit card transactions. Globe Bill would first exchange the order price to RMB (Chinese Currency), 
           using our exchange rates. When charging your credit card, your bank would have to exchange RMB into your currency, using their exchange rates. 
           Therefore, if your bank's exchange rate differs from that of ours, the final charge would vary from the order price. Usually the variation would be within 3% to 5% of your total payment.<br /><br />
           2. Transaction fees<br />
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your bank might charge you for a transaction fee, which varies from 0.5-8 US Dollars. Please note, this fee would not be included in our refund.
          </p>
          <h2>PayPal</h2>
          <p class="shir">
            You may also pay by PayPal.
If you happen to have no PayPal account, you can may still choose to pay by PayPal when you checkout, and you would be directed to a PayPal page where you would follow the instructions to sign up for a PayPal account.
You can also choose to pay by a debit or credit card, or Bill Me Later on the PayPal page.
          </p>