<li class="grp-item">
    <a href="/article/payment-methods.html" class="title aaa">Payment Methods</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/shipping-methods.html" class="title aaa">Shipping Methods</a>
    <span class="p-arrow"></span>
</li>
<li class="grp-item">
    <a href="/article/estimated-delivery-time.html" class="title aaa">Estimated Delivery Time</a>
    <span class="p-arrow"></span>
</li>
