<h2>Please Note:</h2>
         
         <p class="shir" style="text-indent:0">
           1. All customized items without quality issues do not qualify for return or exchange, and neither do the gifts.<br />
           2. All returned items must be in original condition - unworn, unwashed, unaltered, and undamaged.
         </p>
         <h1>Our Policy</h1>
         <p class="shir" style="text-indent:0">
           1. Quality Issues<br />
          Defective or damaged items: If your items were defective or damaged, you would be qualified for a full refund (including shipping cost).
          Color mismatch: The settings of your computer screen may alter the color of the pictures shown on our website. 
          Slight color mismatches between the color of your dress and the color shown on screen may not mean that the dress is defective or mis-shipped. 
          The pictures on the website are only for reference. However, if you are positive that you have received the item in a wrong color, 
          please provide the photos as a proof and contact us for a full refund or exchange for a new one.<br />
          2. Sizing and Fitting Issues<br />
          As all of our dresses are hand-sewn, the finished gown may vary by approximately one inch in either direction of the specified measurements. 
          To ensure that your dress will fit you perfectly, our tailors have reserved additional fabric in the seams to allow minor modifications.
          Please understand that items that do not fit properly but is in accordance with the specifications you ordered do not qualify for return or exchange.
          If your dress size differs for more than one inch from the specifications of your order, we would recommend you to find a local tailor to modify the dress. 
          We would reimburse you the tailoring cost. Please remember to request a receipt from your tailor. The receipt is to be presented when you request reimbursement. 
          Please note that if your order specifications differ greatly from the final sizing request, re-sizing may not be possible. 
          Therefore, we strongly suggest that you check our size chart before placing the order.<br />
          3. Shipping Issues<br />
          If your item was mis-shipped, you would be eligible for a full refund.
          If there was an item missing from your order, please contact our customer service to resend you the missing item or you may ask for a refund.
          In case your package was lost, please contact our customer service for a new package or ask for a full refund.
          If your items were damaged during delivery, please contact our customer service for exchange or return. 
          Please remember to obtain "Proof of Damage" documentation from your delivery carrier and include it in your returned package.<br />
          4. Other Issues<br />
          If you happen to dislike the dress, please contact our customer service for exchange or return. You may get a partial refund of 80% product purchase price. 
          The rest 20% would be charged as a restocking fee. The shipping fee was not to be refunded. And you'll be responsible for the return shipping cost.
          Please note: If your dress is shipped free,the shipping cost would be taken from the refund.
         </p>
         <h1>Return Procedures</h1>
         <p class="shir" style="text-indent:0">
          Step 1: Please send an email to us at support@shirleysdress.com with your Order ID within 7 days upon receiving your order. 
          Please include an explanation and photographs stating the reason for your return. The returns without prior approval from our Customer Service are not acceptable.<br />
          Step 2: Once our Customer Service has approved your request, we will provide you with a return address as well as a Product Return Form that is to be filled in 
          and included in your return package. Please go to your local post office and send the item(s) within 7 days upon receiving the return form.<br />
          *Note: Please don't use expedited courier like UPS, DHL or FedEx. Refunds for the return shipping are calculated using the lowest-cost shipping method. 
          The normal economic Post Office service would be recommended. Please remember to email us the tracking number of the return parcel.<br />
          Step 3: We will process the refund as soon as we have confirmed that the product has the problems you have mentioned and meet our return policy.<br /><br />

          *This return policy does not apply to our business resellers. Please contact us for additional instructions.

         </p>