<p class="shir">
           This page shows you how to choose a shipping method for your order, estimate shipping cost, and gives other further information on shipping process of Shirley's Dress.
           You can choose your preferable Shipping Method:
         </p>
         <h2>Expedited Shipping</h2>
         <p class="shir">
           This shipping method is the fastest available. Delivery times are between 3-5 days to all major destinations. Expedited shipping fee is calculated based on the weight of your order.
         </p>
         <h2>Standard Shipping</h2>
         <p class="shir">
           Standard shipping takes a bit longer than expedited shipping but costs less. Delivery times are between 6-8 days to all major destinations. 
           Standard shipping fee is calculated based on the weight of your order.
         </p>