<div class="size-chart-total">
<!--111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="10">Dress Size Chart</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Waist</td>
        <td class="biaoti" colspan="2">Hips</td>
        <td class="biaoti" colspan="2">Hollow to Floor</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">2</td>
        <td class="inch">32 ½</td>
        <td class="cm">83</td>
        <td class="inch">25 ½</td>
        <td class="cm">65</td>
        <td class="inch">35 ¾</td>
        <td class="cm">91</td>
        <td class="inch">58</td>
        <td class="cm">147</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">4</td>
        <td class="inch">33 ½</td>
        <td class="cm">85</td>
        <td class="inch">26 ½</td>
        <td class="cm">67</td>
        <td class="inch">36 ¾</td>
        <td class="cm">93</td>
        <td class="inch">58</td>
        <td class="cm">147</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">6</td>
        <td class="inch">34 ½</td>
        <td class="cm">88</td>
        <td class="inch">27 ½</td>
        <td class="cm">70</td>
        <td class="inch">37 ¾</td>
        <td class="cm">96</td>
        <td class="inch">59</td>
        <td class="cm">150</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">8</td>
        <td class="inch">35 ½</td>
        <td class="cm">90</td>
        <td class="inch">28 ½</td>
        <td class="cm">72</td>
        <td class="inch">38 ¾</td>
        <td class="cm">98</td>
        <td class="inch">59</td>
        <td class="cm">150</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">10</td>
        <td class="inch">36 ½</td>
        <td class="cm">93</td>
        <td class="inch">29 ½</td>
        <td class="cm">75</td>
        <td class="inch">39 ¾</td>
        <td class="cm">101</td>
        <td class="inch">60</td>
        <td class="cm">152</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">12</td>
        <td class="inch">38</td>
        <td class="cm">97</td>
        <td class="inch">31</td>
        <td class="cm">79</td>
        <td class="inch">41 ¼</td>
        <td class="cm">105</td>
        <td class="inch">60</td>
        <td class="cm">152</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">14</td>
        <td class="inch">39 ½</td>
        <td class="cm">100</td>
        <td class="inch">32 ½</td>
        <td class="cm">83</td>
        <td class="inch">42 ¾</td>
        <td class="cm">109</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">16</td>
        <td class="inch">41</td>
        <td class="cm">104</td>
        <td class="inch">34</td>
        <td class="cm">86</td>
        <td class="inch">44 ¼</td>
        <td class="cm">112</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
</table>
<!--111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 end-->

<!--2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="10">Plus Size Dress Size Chart</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Waist</td>
        <td class="biaoti" colspan="2">Hips</td>
        <td class="biaoti" colspan="2">Hollow to Floor</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">16W</td>
        <td class="inch">43</td>
        <td class="cm">109</td>
        <td class="inch">36 ¼</td>
        <td class="cm">92</td>
        <td class="inch">45 ½</td>
        <td class="cm">116</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">18W</td>
        <td class="inch">45</td>
        <td class="cm">114</td>
        <td class="inch">38 ½</td>
        <td class="cm">98</td>
        <td class="inch">47 ½</td>
        <td class="cm">121</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">20W</td>
        <td class="inch">47</td>
        <td class="cm">119</td>
        <td class="inch">40 ¾</td>
        <td class="cm">104</td>
        <td class="inch">49 ½</td>
        <td class="cm">126</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">22W</td>
        <td class="inch">49</td>
        <td class="cm">124</td>
        <td class="inch">43</td>
        <td class="cm">109</td>
        <td class="inch">51 ½</td>
        <td class="cm">131</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">24W</td>
        <td class="inch">51</td>
        <td class="cm">130</td>
        <td class="inch">45 ¼</td>
        <td class="cm">115</td>
        <td class="inch">53 ½</td>
        <td class="cm">136</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">26W</td>
        <td class="inch">53</td>
        <td class="cm">135</td>
        <td class="inch">47 ½</td>
        <td class="cm">121</td>
        <td class="inch">55 ½</td>
        <td class="cm">141</td>
        <td class="inch">61</td>
        <td class="cm">155</td>
    </tr>
</table>
<!--2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222 end-->

<!--333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="10">Flower Girl Dresses Size Chart</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Waist</td>
        <td class="biaoti" colspan="2">Hips</td>
        <td class="biaoti" colspan="2">Hollow to Floor</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">2</td>
        <td class="inch">21</td>
        <td class="cm">53</td>
        <td class="inch">20</td>
        <td class="cm">51</td>
        <td class="inch">20</td>
        <td class="cm">51</td>
        <td class="inch">33</td>
        <td class="cm">84</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">3</td>
        <td class="inch">22</td>
        <td class="cm">56</td>
        <td class="inch">21</td>
        <td class="cm">53</td>
        <td class="inch">21</td>
        <td class="cm">53</td>
        <td class="inch">35</td>
        <td class="cm">89</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">4</td>
        <td class="inch">23</td>
        <td class="cm">58</td>
        <td class="inch">22</td>
        <td class="cm">56</td>
        <td class="inch">22</td>
        <td class="cm">56</td>
        <td class="inch">38</td>
        <td class="cm">97</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">5</td>
        <td class="inch">24</td>
        <td class="cm">61</td>
        <td class="inch">23</td>
        <td class="cm">58</td>
        <td class="inch">23</td>
        <td class="cm">58</td>
        <td class="inch">40</td>
        <td class="cm">102</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">6</td>
        <td class="inch">25</td>
        <td class="cm">64</td>
        <td class="inch">24</td>
        <td class="cm">61</td>
        <td class="inch">25</td>
        <td class="cm">64</td>
        <td class="inch">41</td>
        <td class="cm">104</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">7</td>
        <td class="inch">26</td>
        <td class="cm">66</td>
        <td class="inch">25</td>
        <td class="cm">64</td>
        <td class="inch">26</td>
        <td class="cm">66</td>
        <td class="inch">42</td>
        <td class="cm">107</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">8</td>
        <td class="inch">27</td>
        <td class="cm">69</td>
        <td class="inch">26</td>
        <td class="cm">66</td>
        <td class="inch">27</td>
        <td class="cm">69</td>
        <td class="inch">43</td>
        <td class="cm">109</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">9</td>
        <td class="inch">28</td>
        <td class="cm">71</td>
        <td class="inch">27</td>
        <td class="cm">69</td>
        <td class="inch">29</td>
        <td class="cm">74</td>
        <td class="inch">44</td>
        <td class="cm">112</td>
    </tr>

    <tr>
        <td class="cm" colspan="2">10</td>
        <td class="inch">29</td>
        <td class="cm">74</td>
        <td class="inch">28</td>
        <td class="cm">71</td>
        <td class="inch">31</td>
        <td class="cm">79</td>
        <td class="inch">47</td>
        <td class="cm">119</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">11</td>
        <td class="inch">30 ½</td>
        <td class="cm">77</td>
        <td class="inch">29</td>
        <td class="cm">74</td>
        <td class="inch">33</td>
        <td class="cm">84</td>
        <td class="inch">48</td>
        <td class="cm">122</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">12</td>
        <td class="inch">32</td>
        <td class="cm">81</td>
        <td class="inch">30</td>
        <td class="cm">76</td>
        <td class="inch">34</td>
        <td class="cm">86</td>
        <td class="inch">50</td>
        <td class="cm">127</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">13</td>
        <td class="inch">33</td>
        <td class="cm">84</td>
        <td class="inch">31</td>
        <td class="cm">79</td>
        <td class="inch">34 ½</td>
        <td class="cm">88</td>
        <td class="inch">51</td>
        <td class="cm">130</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">14</td>
        <td class="inch">34</td>
        <td class="cm">86</td>
        <td class="inch">32</td>
        <td class="cm">81</td>
        <td class="inch">35</td>
        <td class="cm">89</td>
        <td class="inch">52</td>
        <td class="cm">132</td>
    </tr>
</table>
<!--333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333 end-->

<!--4444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="10">Junior Bridesmaid Dresses Size Chart</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Waist</td>
        <td class="biaoti" colspan="2">Hips</td>
        <td class="biaoti" colspan="2">Hollow to Floor</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J4</td>
        <td class="inch">22</td>
        <td class="cm">56</td>
        <td class="inch">20</td>
        <td class="cm">51</td>
        <td class="inch">25</td>
        <td class="cm">64</td>
        <td class="inch">42</td>
        <td class="cm">107</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J6</td>
        <td class="inch">24</td>
        <td class="cm">61</td>
        <td class="inch">22</td>
        <td class="cm">56</td>
        <td class="inch">27</td>
        <td class="cm">69</td>
        <td class="inch">45</td>
        <td class="cm">114</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J8</td>
        <td class="inch">26</td>
        <td class="cm">66</td>
        <td class="inch">24</td>
        <td class="cm">61</td>
        <td class="inch">29</td>
        <td class="cm">74</td>
        <td class="inch">48</td>
        <td class="cm">122</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J10</td>
        <td class="inch">28</td>
        <td class="cm">71</td>
        <td class="inch">26</td>
        <td class="cm">66</td>
        <td class="inch">31</td>
        <td class="cm">79</td>
        <td class="inch">50</td>
        <td class="cm">127</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J12</td>
        <td class="inch">30</td>
        <td class="cm">76</td>
        <td class="inch">28</td>
        <td class="cm">71</td>
        <td class="inch">33</td>
        <td class="cm">84</td>
        <td class="inch">51</td>
        <td class="cm">130</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J14</td>
        <td class="inch">32</td>
        <td class="cm">81</td>
        <td class="inch">30</td>
        <td class="cm">76</td>
        <td class="inch">35</td>
        <td class="cm">89</td>
        <td class="inch">53</td>
        <td class="cm">135</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">J16</td>
        <td class="inch">34</td>
        <td class="cm">86</td>
        <td class="inch">32</td>
        <td class="cm">81</td>
        <td class="inch">37</td>
        <td class="cm">94</td>
        <td class="inch">55</td>
        <td class="cm">140</td>
    </tr>
</table>
<!--4444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444 end-->

<!--5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="8">Wrap Size(1)</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Shoulder to Bust</td>
        <td class="biaoti" colspan="2">Shoulder to waist</td>
        <!--               <td class="biaoti" colspan="2">Bust point to bust point</td>
                       <td class="biaoti" colspan="2">Shoulder</td>
                       <td class="biaoti" colspan="2">Armhole</td>-->
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">2</td>
        <td class="inch">32 ½</td>
        <td class="cm">83</td>
        <td class="inch">9 ¾</td>
        <td class="cm">24 ½</td>
        <td class="inch">15 ¾</td>
        <td class="cm">40</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">4</td>
        <td class="inch">33 ½</td>
        <td class="cm">85</td>
        <td class="inch">10</td>
        <td class="cm">25</td>
        <td class="inch">16 ¼</td>
        <td class="cm">41</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">6</td>
        <td class="inch">34 ½</td>
        <td class="cm">88</td>
        <td class="inch">10</td>
        <td class="cm">25 ½</td>
        <td class="inch">16 ½</td>
        <td class="cm">42</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">8</td>
        <td class="inch">35 ½</td>
        <td class="cm">90</td>
        <td class="inch">10 ¼</td>
        <td class="cm">26</td>
        <td class="inch">17</td>
        <td class="cm">43</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">10</td>
        <td class="inch">36 ½</td>
        <td class="cm">93</td>
        <td class="inch">10 ½</td>
        <td class="cm">26 ½</td>
        <td class="inch">17 ½</td>
        <td class="cm">44</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">12</td>
        <td class="inch">38</td>
        <td class="cm">97</td>
        <td class="inch">10 ¾</td>
        <td class="cm">27</td>
        <td class="inch">17 ¾</td>
        <td class="cm">45</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">14</td>
        <td class="inch">39 ½</td>
        <td class="cm">100</td>
        <td class="inch">11</td>
        <td class="cm">27 ¼</td>
        <td class="inch">18 ¼</td>
        <td class="cm">46</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">16</td>
        <td class="inch">41</td>
        <td class="cm">104</td>
        <td class="inch">11</td>
        <td class="cm">28</td>
        <td class="inch">18 ½</td>
        <td class="cm">47</td>

    </tr>
</table>
<!--5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555 end-->

<!--6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="8">Wrap Size(2)</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>

        <td class="biaoti" colspan="2">Bust point to bust point</td>
        <td class="biaoti" colspan="2">Shoulder</td>
        <td class="biaoti" colspan="2">Armhole</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">2</td>
        <td class="inch">7</td>
        <td class="cm">17 ½</td>
        <td class="inch">14 ¾</td>
        <td class="cm">37</td>
        <td class="inch">15</td>
        <td class="cm">38</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">4</td>
        <td class="inch">7</td>
        <td class="cm">18</td>
        <td class="inch">15</td>
        <td class="cm">38</td>
        <td class="inch">15 ½</td>
        <td class="cm">39</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">6</td>
        <td class="inch">7 ½</td>
        <td class="cm">18 ½</td>
        <td class="inch">15</td>
        <td class="cm">38</td>
        <td class="inch">16</td>
        <td class="cm">40 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">8</td>
        <td class="inch">7 ½</td>
        <td class="cm">19</td>
        <td class="inch">15 ½</td>
        <td class="cm">39</td>
        <td class="inch">16 ½</td>
        <td class="cm">41 ½</td>


    </tr>
    <tr>
        <td class="cm" colspan="2">10</td>
        <td class="inch">7 ¾</td>
        <td class="cm">19 ½</td>
        <td class="inch">15 ¾</td>
        <td class="cm">40</td>
        <td class="inch">16 ¾</td>
        <td class="cm">42 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">12</td>
        <td class="inch">8</td>
        <td class="cm">20</td>
        <td class="inch">16 ¼</td>
        <td class="cm">41</td>
        <td class="inch">17 ½</td>
        <td class="cm">44</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">14</td>
        <td class="inch">8</td>
        <td class="cm">20 ½</td>
        <td class="inch">16 ¼</td>
        <td class="cm">42</td>
        <td class="inch">18</td>
        <td class="cm">45 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">16</td>
        <td class="inch">8 ¼</td>
        <td class="cm">21</td>
        <td class="inch">17</td>
        <td class="cm">43</td>
        <td class="inch">18 ½</td>
        <td class="cm">47</td>

    </tr>
</table>
<!--6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666 end-->

<!--77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="8">Plus Size Wrap Size(1)</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>
        <td class="biaoti" colspan="2">Bust</td>
        <td class="biaoti" colspan="2">Shoulder to Bust</td>
        <td class="biaoti" colspan="2">Shoulder to waist</td>
        <!--               <td class="biaoti" colspan="2">Bust point to bust point</td>
                       <td class="biaoti" colspan="2">Shoulder</td>
                       <td class="biaoti" colspan="2">Armhole</td>-->
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">16W</td>
        <td class="inch">43</td>
        <td class="cm">109</td>
        <td class="inch">11 ½</td>
        <td class="cm">29</td>
        <td class="inch">19 ½</td>
        <td class="cm">49</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">18W</td>
        <td class="inch">45</td>
        <td class="cm">114</td>
        <td class="inch">11 ¾</td>
        <td class="cm">29 ½</td>
        <td class="inch">19 ¾</td>
        <td class="cm">50</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">20W</td>
        <td class="inch">47</td>
        <td class="cm">119</td>
        <td class="inch">12</td>
        <td class="cm">30</td>
        <td class="inch">20</td>
        <td class="cm">51</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">22W</td>
        <td class="inch">49</td>
        <td class="cm">124</td>
        <td class="inch">12 ¼</td>
        <td class="cm">31</td>
        <td class="inch">20 ½</td>
        <td class="cm">52</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">24W</td>
        <td class="inch">51</td>
        <td class="cm">130</td>
        <td class="inch">12 ¼</td>
        <td class="cm">31</td>
        <td class="inch">21</td>
        <td class="cm">53 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">26W</td>
        <td class="inch">53</td>
        <td class="cm">135</td>
        <td class="inch">12 ½</td>
        <td class="cm">31 ½</td>
        <td class="inch">21 ½</td>
        <td class="cm">54 ½</td>

    </tr>
</table>
<!--77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777 end-->

<!--88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888-->
<table class="sctable" border="0" cellspacing="0" cellpadding="0">
    <tr><th colspan="8">Plus Size Wrap Size(2)</th></tr>
    <tr>
        <td class="biaoti" colspan="2">Size</td>

        <td class="biaoti" colspan="2">Bust point to bust point</td>
        <td class="biaoti" colspan="2">Shoulder</td>
        <td class="biaoti" colspan="2">Armhole</td>
    </tr>
    <tr>
        <td class="cm" colspan="2">&nbsp;</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>
        <td class="inch">inch</td>
        <td class="cm">cm</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">16W</td>
        <td class="inch">8 ¾</td>
        <td class="cm">22</td>
        <td class="inch">17 ¾</td>
        <td class="cm">45</td>
        <td class="inch">19 ½</td>
        <td class="cm">49</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">18W</td>
        <td class="inch">9</td>
        <td class="cm">22 ½</td>
        <td class="inch">18 ½</td>
        <td class="cm">46</td>
        <td class="inch">20 ¾</td>
        <td class="cm">52</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">20W</td>
        <td class="inch">9</td>
        <td class="cm">23</td>
        <td class="inch">18 ½</td>
        <td class="cm">47</td>
        <td class="inch">20 ¾</td>
        <td class="cm">52 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">22W</td>
        <td class="inch">9 ¼</td>
        <td class="cm">23 ½</td>
        <td class="inch">19</td>
        <td class="cm">48</td>
        <td class="inch">21 ½</td>
        <td class="cm">54 ½</td>


    </tr>
    <tr>
        <td class="cm" colspan="2">24W</td>
        <td class="inch">10 ¼</td>
        <td class="cm">26</td>
        <td class="inch">19</td>
        <td class="cm">48</td>
        <td class="inch">21 ¾</td>
        <td class="cm">55 ½</td>

    </tr>
    <tr>
        <td class="cm" colspan="2">26W</td>
        <td class="inch">10 ¾</td>
        <td class="cm">27</td>
        <td class="inch">19 ½</td>
        <td class="cm">49</td>
        <td class="inch">22 ¾</td>
        <td class="cm">57 ¾</td>

    </tr>

</table>
<!--888888888888888888888888888888888888888888888888888888888888888888888888888888888888888 end-->
</div>